### PR TITLE
BUG failed test of pouchdb executing insert -> remove -> insert -> remove

### PR DESCRIPTION
**Pull request by nisarpeitang**
## This PR contains:
A failed testcase of PouchDB adapter when executing the routine insert -> remove -> insert -> remove

## Describe the problem you have without this PR
The second removal operation will fail due to incorrect revision number. This bug only happens when using PouchDB storage.

```
RxError (COL19): RxError (COL19):
Document update conflict. When changing a document you must work on the previous revision
Given parameters: {
collection:"mycollection"
id:"test1"
error:{
  "isError": true,
  "status": 409,
  "documentId": "test1",
  "writeRow": {
    "document": {
      "name": "test1",
      "gender": "male",
      "birthyear": 2000,
      "_meta": {
        "lwt": 1654692585166
      },
      "_deleted": true,
      "_attachments": {},
      "_rev": "2-c3801976cb7d9f46ed6227d2b76c5ac8"
    },
    "previous": {
      "name": "test1",
      "gender": "male",
      "birthyear": 2000,
      "_meta": {
        "lwt": 1
      },
      "_deleted": false,
      "_attachments": {},
      "_rev": "1-d29c95b1150dcdbd7e5140fbc5f9be7b"
    }
  },
  "documentInDb": {
    "gender": "male",
    "birthyear": 2000,
    "_attachments": {},
    "_rev": "3-d29c95b1150dcdbd7e5140fbc5f9be7b",
    "name": "test1",
    "_deleted": false,
    "_meta": {
      "lwt": 1654692585158
    }
  }
}
data:{
  "name": "test1",
  "gender": "male",
  "birthyear": 2000,
  "_meta": {
    "lwt": 1
  },
  "_deleted": true,
  "_attachments": {},
  "_rev": "1-d29c95b1150dcdbd7e5140fbc5f9be7b"
}}
```

## Todos
- [ ] Tests
- [ ] Documentation
- [ ] Typings
- [ ] Changelog

### CODE REVIEW

**Comment by pubkey** [comment]
Might be equal to https://github.com/pubkey/rxdb/pull/3812#issuecomment-1148711613
Can you check if this works with plain pouchdb? If not, this is a pouchdb bug and should reported at the pouchdb repo.

**Comment by nisarpeitang** [comment]
I created a [gist](https://gist.github.com/nisarpeitang/3a5f0666371f4a6da1b80ea8348ee4ed) to verify the same routine on plain pouchdb and there's no error.

Output:
```
1-5191862503c07f65ec74a15df4a0aa86
{
  total_rows: 1,
  offset: 0,
  rows: [ { id: 'test', key: 'test', value: [Object] } ]
}
{ total_rows: 0, offset: 0, rows: [] }
3-7c210315d93a3c532db44e80e963e74f
{
  total_rows: 1,
  offset: 0,
  rows: [ { id: 'test', key: 'test', value: [Object] } ]
}
{ total_rows: 0, offset: 0, rows: [] }
```

The possible reason is that RxDB reset the rev when recreating the document with same id while pouchdb does not.

**Comment by pubkey** [comment]
I investigated a bit. Thank you for making the tests, that really helped.

After the second insert, pouchDB works on the revision height 3 `3-7c21031...` while RxDB starts from 1 again `1-18fe9e5...`.
I think this behavior has changed in the latest PouchDB release.
The best solution in my opinion would be that RxDB also detects that the deleted document is re-inserted and then also inserts with revision height 3 instead of 1.

You can make a PR if you need this fixed.

**Comment by nisarpeitang** [comment]
I will try to submit a PR to fix this issue.

**Comment by pubkey** [comment]
Fixed here https://github.com/pubkey/rxdb/pull/3886

**Pull request closed without merging**
