### PR TITLE
Add support to specify location and iosDatabaseLocation

### PR DESCRIPTION
**Pull request by EugeniaM**
## This PR contains:
 - A BUGFIX

## Describe the problem you have without this PR
When using 'cordova-sqlite' adapter (which uses native Cordova SQLite as its backing store) we need RxDB to create an instance of PouchDb with specified **location** or **iosDatabaseLocation** (these are required by cordoa sqlite plugin).
So an instance of PouchDb should be created like this:
```
new PouchDB('dbname', {adapter: 'cordova-sqlite', location: 'default'})
```
or this
```
new PouchDB('dbname', {adapter: 'cordova-sqlite', iosDatabaseLocation: 'default'})
```
The current implementation of RxDB let us specify only adapter.
This PR will give the possibility to specify location or iosDatabaseLocation in options property when creating database
```
await RxDB.create({
  name: 'dbname',
  adapter: 'cordova-sqlite',
  password: 'passwordPasswordPassword',
  options: { location: 'default' }
});
```

## Todos
- [ ] Documentation

### CODE REVIEW

**Comment by pubkey** [comment]
Hi @EugeniaM 
Sorry I didn't have the time to answer this weekend.

I have the fear that using the whole options-object merged into the pouchdb-settings, can cause conflicts.

Can we change it to introduce `pouchSettings` in RxDatabase, like it's done in [RxCollection](https://github.com/pubkey/rxdb/blob/master/src/typings/rx-collection.d.ts#L32)

**Comment by EugeniaM** [comment]
@pubkey 
Sure, no problem. I will change it in new commit to this PR

**Comment by EugeniaM** [comment]
@pubkey 
Added new commit to [https://github.com/pubkey/rxdb/pull/567](https://github.com/pubkey/rxdb/pull/567)

**Comment by pubkey** [comment]
Wow. Thank you for that awesome PR. Merged.

**Pull request merged**
