### PR TITLE
build: migrate from tslint to eslint

### PR DESCRIPTION
**Pull request by raveclassic**
Hey @pubkey! As I noted in https://github.com/pubkey/rxdb/issues/3279#issuecomment-878381165, I think I could help with code style consistency a bit.

## Context
The testing pipeline in this repo uses [tslint](https://palantir.github.io/tslint/) to lint `*.ts` files which [has been deprecated](https://blog.palantir.com/tslint-in-2019-1a144c2317a9) since 2019 as is no longer maintained.
Besides being outdated, `tslint` fails to do some useful checks on typescript code which are supported by `eslint`.
Finally, `tslint` contains several bugs like https://github.com/palantir/tslint/issues/3314 which make it fail to lint `*.d.ts` files and it seems they will never be fixed and it's strongly suggested by its maintainers to migrate to [eslint](https://eslint.org/). 

Without a new linter it's impossible to keep the whole codebase consistent, easy to read and follow, easy to maintain.

## Proposal
The PR suggests to break the migration into steps so that it would be much easier to review changes.
Initially, it's suggested to replicate the configuration and stick to original code style. However, there will be issues in the code because `eslint` rules are a bit different from `tslint` rules. All issues should be suppressed to keep the code intact.
Next, it's suggested to open several PRs which would incrementally update the code to be more fully aligned with the rules.
  1. move old rules from `.eslintrc.json` to the section for `/config/*.js` files because currently `eslint` is used only for that directory
  2. replace `tslint` with `eslint` and replicate the ruleset from `tslint.json` to `.eslintrc.json`. There's a [tool](https://github.com/typescript-eslint/tslint-to-eslint-config) that _partially_ automates the transition. Remove all files and dependencies related to `tslint`
  3. at this moment, there will be a _ton_ of linting errors because part of the code is not checked at all, and another part is not fully aligned with the rules, because `tslint` failed to check them. Here, it's suggested to keep to code intact and to disable the errors in `.eslintrc.json`.
  4. for each disabled rule, open a PR enabling that rule back and _automatically_ updating the code using `--fix` flag so that it could be reviewed easier

## Alternatives
There's a [plugin](https://www.npmjs.com/package/@typescript-eslint/eslint-plugin-tslint) for `eslint` that allows to use obsolete `tslint.json` in `eslint` but it still uses deprecated `tslint` linter under the hood which doesn't seem to solve the deprecation.

## Summary
This PR contains the steps 1, 2 and 3, and if it gets approved I'll open more PRs bringing disabled eslint rules back. Looking forward to some feedback and thank you for your time!

### CODE REVIEW

**Comment by pubkey** [comment]
Hi @raveclassic 
thank you for the PR.
I am currently trying to figure out how to run the ci on PRs to the release branch.
I will merge this once the ci is green.

**Comment by pubkey** [comment]
Can you make the PR against the master branch? I already merged release/10.0.0 into the master.

**Comment by pubkey** [comment]
@raveclassic can you rebase this to the current master branch?

**Comment by raveclassic** [comment]
@pubkey I'm sorry for the delay, I'm on vacation without access to my laptop and I will rebase the PR on July 27th.

**Comment by raveclassic** [comment]
Hey @pubkey, sorry for being late, I've rebased the branch on latest `master`

**Comment by raveclassic** [comment]
Hey @pubkey, is there anything else I should do here?

**Comment by pubkey** [comment]
@raveclassic Sorry, I totally forgot this PR.
The changes look good, I will merge when the CI is green.

Thank you for your work.

**Comment by raveclassic** [comment]
Thanks for the feedback and for updating the `.eslintignore`!

**Pull request merged**
