### PR TITLE
blocked 'e' from team size input

### PR DESCRIPTION
**Pull request by DDeerrpp**

### CODE REVIEW

**Comment by DDeerrpp** [comment]
Pretty sure it really doesn't do a difference but just to block the letter 'e' from being input as it doesn't seem like it's needed.

**Comment by pubkey** [comment]
Nice :)
Should we also block the minus symbol `-` ?

**Comment by DDeerrpp** [comment]
Yea I forgot, lemme add see if it can block the period and minus symbols too

**Comment by DDeerrpp** [comment]
Alright it should block the keycodes 'e', '.', and '-' now in that input number type!

**Comment by pubkey** [comment]
Thank you, merged.

**Pull request merged**
