### PR TITLE
feature request: populate multiple paths like in mongoose

### PR DESCRIPTION
**Pull request by darkowic**
## This PR contains:
**Feature request: populate multiple paths like in mongoose**
https://mongoosejs.com/docs/populate.html#populating-multiple-paths

## Describe the problem you have without this PR
There are cases where you want to easily populate fields for multiple find results. Current option is only to run this as separate async array looping and its not convenient to use.

### CODE REVIEW

**Comment by darkowic** [comment]
Basically, the final goal would be to have an option to synchronously access the related document properties.

**Comment by pubkey** [comment]
Hi @darkowic 
I understand the use case but I think this can be better implemented as own RxDB plugin.
We can link to it from [here](https://github.com/pubkey/rxdb/blob/master/docs-src/third-party-plugins.md)

**Comment by darkowic** [comment]
Working on some workarounds yesterday to make it work, I also realized that calling `populate` is not modifying the document, but just returns the populated document. In Mongoose: https://mongoosejs.com/docs/populate.html#population the document is updated with all the fields and can be directly accessed from the parent. This is sooo much easier to use. Do you think its all possible via plugin? Together with handling obserability etc? (I'm really new user of this library)

**Comment by pubkey** [comment]
RxDB works on the plain documents data so that it can de-duplicate them in the cache.
That is also why there are no "select" queries.
Of course you can build whatever plugin you like which also mutates the plain document data, but as said, that should be done in your plugin.

When I started RxDB some years ago, a big goal was to let it behave similar to mongoose. But over the time it became clear that mongoose has many problems and tracking their behavior is often not the best solution. Especially when it comes to have correct typescript support.

**Pull request closed without merging**
