### PR TITLE
Bugfix/6064

### PR DESCRIPTION
**Pull request by marnec**
## This PR contains:
A test case showing that firestore replication fails pulling documents

## Describe the problem you have without this PR
https://github.com/pubkey/rxdb/issues/6064

### CODE REVIEW

**Comment by marnec** [comment]
I realized the name of the the branch is extremely misleading. This is not a bugfix, I just add the test case showing the fierstore-replication fails. I'm sorry it was late at night

**Comment by pubkey** [comment]
The ci fails with `[2024-06-04T21:45:24.492Z]  @firebase/firestore: Firestore (10.12.2): GrpcConnection RPC 'Write' stream 0x7cc768c7 error. Code: 14 Message: 14 UNAVAILABLE: No connection established. Last error: connect ECONNREFUSED 127.0.0.1:8080 (2024-06-04T21:45:24.487Z)`

Is that the error you are trying to reproduce?

**Comment by marnec** [comment]
No, 
the error reproduced by this branch is the one documented in https://github.com/pubkey/rxdb/issues/6064.
I didn't mess with the ci scripts and I only modified the bug_report template and added a script in package.json to run the test_case.

**Comment by pubkey** [comment]
@marnec Can you change the PR so that the CI reproduces the actual problem?

**Pull request closed without merging**
