### PR TITLE
Bug example: key compression enabled with boolean indexes on dexie

### PR DESCRIPTION
**Pull request by gizm0bill**
Hello,
I'm opening this PR to demo a bug regarding key compression and boolean indexes with dexie storage.
So when key compression is added and there are some boolean indexes defined in the schema, no results are returned when using that index in a query.
The problem basically boils down to the compression flag and from/toStorage "dance" when inserting and querying documents

### CODE REVIEW

**Comment by pubkey** [comment]
Primary key must always be a string.

**Comment by gizm0bill** [comment]
Ok I have modified it but still fails. You can also look in the browser's indexeddb storage, indexes for `[_deleted+__a+passportId]` and `[_deleted+__b+__c+__a+passportId]` are empty

**Comment by pubkey** [comment]
You did not set maxLength for the primary key. Please read the docs and enable the dev-mode plugin in your setup.

**Comment by gizm0bill** [comment]
I have updated the unit, please take a look now

**Comment by pubkey** [comment]
@gizm0bill Thank you. I can reproduce this now, I will check.

**Comment by gizm0bill** [comment]
Danke!

**Pull request closed without merging**
