### PR TITLE
fix behaviour to fit with documentation in back channel use.

### PR DESCRIPTION
**Pull request by mmouterde**
## This PR contains:
 - A BUGFIX

## Describe the problem you have without this PR
Actual:
- no push on document updates if live=false
- no way to disable polling: liveInterval=0 is rejected by ensureNotFalsy() line 581 when live=true

Expected:
- do not poll if liveInterval=0 and live=true
- push triggered on document updates

### CODE REVIEW

**Comment by pubkey** [comment]
Code looks good.
We need at least 1 unit test to ensure the behavior is correct.

**Comment by pubkey** [comment]
I mean we need a test that reproduces the replication behavior that did not work without the fix.

**Comment by mmouterde** [comment]
Sure! I'm working such tests.
Not so easy without mock or `assert.CallTracker` to test function calls.
Do you have any example or way you usually test this kind of test ?

**Comment by pubkey** [comment]
Looks good to me, I merged it. Thank you @mmouterde

**Pull request merged**
