### PR TITLE
bug report for lte + gte + sort failure

### PR DESCRIPTION
**Pull request by inverted-capital**
## This PR contains:
 - A BUG REPORT

## Todos 
- [ x ] Tests

### CODE REVIEW

**Comment by pubkey** [comment]
Can you try if this works with plain pouchdb?
Because if not, the issue should be created in the pouchdb repo.

**Comment by inverted-capital** [comment]
Sir, this test fails on `npm run test:node:lokijs`

**Comment by pubkey** [comment]
Ah sry I wrote my comment before the CI has run.
So does it work to run that query with plain LokiJS?

**Comment by inverted-capital** [comment]
The way you have set up CI is a really good way of segmenting bugs, particularly as you support multiple environments.  I like this idea of using pull requests instead of issues - makes communication really clear.

**Comment by pubkey** [comment]
Ok I looked into this.
So RxDB correctly joins the query chain to end with the following mango query:
```json
{
    "selector": {
        "$and": [
            {
                "_deleted": false
            },
            {
                "passportId": {
                    "$gte": "pooulzxvwpzq",
                    "$lte": "pooulzxvwpzq~"
                }
            }
        ]
    },
    "limit": 1,
    "sort": [
        {
            "passportId": "desc"
        }
    ]
}
```
So this looks correct.
Can you try to reproduce this with plain LokiJS? Very likely it is a bug in the LokiJS query.

Also I am not sure if your query does what you think.
For example in your test if the primary is `pooulzxvwpzq`. Then after the sorting by primary **descending**, the query results looks like:

```json
[
    {
        "passportId": "yrhgbajivudp",
        "firstName": "Xzavier",
        "lastName": "Cummings",
        "age": 41,
        "_rev": "1-23678b9716ee56128b17d28237e95197",
        "_deleted": false,
        "_attachments": {},
        "$lastWriteAt": 1644007737414,
        "$loki": 5
    },
    {
        "passportId": "wfcsniwsjeay",
        "firstName": "Felipe",
        "lastName": "Wisoky",
        "age": 11,
        "_rev": "1-4845971c78683480e92212ca14ad0ba4",
        "_deleted": false,
        "_attachments": {},
        "$lastWriteAt": 1644007737408,
        "$loki": 2
    },
    {
        "passportId": "uyfykbabmtej",
        "firstName": "Jonathan",
        "lastName": "Beer",
        "age": 27,
        "_rev": "1-12fa03b74ea2cbaaa0780d543808e0ce",
        "_deleted": false,
        "_attachments": {},
        "$lastWriteAt": 1644007737420,
        "$loki": 8
    },
    {
        "passportId": "slblezlhgjsg",
        "firstName": "Dimitri",
        "lastName": "Mante",
        "age": 18,
        "_rev": "1-2d9b972387f8b7875027bc2527d94ccc",
        "_deleted": false,
        "_attachments": {},
        "$lastWriteAt": 1644007737410,
        "$loki": 3
    },
    {
        "passportId": "pooulzxvwpzq",
        "firstName": "Rhea",
        "lastName": "Cremin",
        "age": 44,
        "_rev": "1-bafc70621ed856d207049b1151694734",
        "_deleted": false,
        "_attachments": {},
        "$lastWriteAt": 1644007737406,
        "$loki": 1
    }
]
```

And because it is a findOne query, it will take the first of them. Which is the one with id `yrhgbajivudp`.
So your test must fail.

**Comment by pubkey** [comment]
But strange that it does not fail on the other storages. There must be something I am missing out.

**Comment by inverted-capital** [comment]
I think the query is being assembled or interpreted wrong - only the $gte is being honoured, not the $lte part.  If the query was expanded to be:
```js 
{
    "selector": {
        "$and": [
            {
                "_deleted": false
            },
            {
                "passportId": {
                    "$gte": "pooulzxvwpzq"
                }
            },
            {
                "passportId": {
                    "$lte": "pooulzxvwpzq~"
                }
            }
        ]
    },
    "limit": 1,
    "sort": [
        {
            "passportId": "desc"
        }
    ]
}
```

Then I would expect it to work ?  I'll try get something going in raw lokijs

**Comment by inverted-capital** [comment]
Additionally, if the order of the gte() and lte() calls is reversed, it would appear that only the first call is honoured.  so:
```js
                    "$gte": "pooulzxvwpzq",
                    "$lte": "pooulzxvwpzq~"
``` 
gives a different result to:
```js
                    "$lte": "pooulzxvwpzq~",
                    "$gte": "pooulzxvwpzq"
```

**Comment by pubkey** [comment]
Any update on this?

**Comment by pubkey** [comment]
Closing this. Ping me if you are still working on it.

**Pull request closed without merging**
