### PR TITLE
Undefined is now treated as null https://github.com/pubkey/rxdb/issue…

### PR DESCRIPTION
**Pull request by 1yasa**
## This PR contains:

A unit test of `rxdb@v15.0.0` for inserting a undefined value(this value is optional), rxdb will throw error cause by rxdb tranformed value to null.

## Describe the problem you have without this PR

https://github.com/pubkey/rxdb/issues/5414

### CODE REVIEW

**Comment by pubkey** [comment]
Your test throws a conflict error which is correct because at the second insert the document already exists.

**Comment by 1yasa** [comment]
> Your test throws a conflict error which is correct because at the second insert the document already exists.

I tested non-CRDT insertion, insertCRDT in CRDT mode, and regular insert in CRDT mode. The test results indicate that the first two methods meet expectations, but the result of insert in CRDT mode is incorrect.

截屏2023-12-26 15 07 23

**Comment by pubkey** [comment]
Since RxDB v15 we use the [mingo library](https://github.com/kofrasa/mingo) for the nosql-updates. It seems that mingo strips away fields with undefined or replaces the value with null.
So this was causing the dev-mode check to throw an error because the outcoming documents where not equal.

**Comment by 1yasa** [comment]
> Since RxDB v15 we use the [mingo library](https://github.com/kofrasa/mingo) for the nosql-updates. It seems that mingo strips away fields with undefined or replaces the value with null. So this was causing the dev-mode check to throw an error because the outcoming documents where not equal.
> 
> I added a fix for the check here: #5445 However you might want to do a PR to the mingo lib to ensure correct merging of undefined fields.

🙏

**Pull request closed without merging**
