### PR TITLE
example with quasar-framework

### PR DESCRIPTION
**Pull request by TobyMosque**
## This PR contains:
an new example

### CODE REVIEW

**Comment by pubkey** [comment]
We need some end2end tests. See the [angular example](https://github.com/pubkey/rxdb/blob/master/examples/angular/test/e2e.test.js) for reference.

**Comment by pubkey** [comment]
Any update on this?

**Comment by TobyMosque** [comment]
I'm trying to expand the current example, if u prefer u can close that for now, I'll reopen when i finish the improvements/tests/cicd.

**Comment by TobyMosque** [comment]
@pubkey done.
image
image

**Comment by pubkey** [comment]
Sorry for not mentioning this before. We should use the testcafe module for testing. In the future the goal is to reuse the test-runner for all examples and run the exact same tests on all of these.
Also please do not commit you yarn.lock file.

**Pull request closed without merging**
