### PR TITLE
Replication doc key

### LINKED ISSUE #3394: Feature Request: Need a way to reset graphql replication
## Case
Feature Request

## Issue

I'd like to add a `reset` function on `RxGraphQLReplicationState`. We need this because we currently have a way for a user to delete data on our server (but not in their local app) Right now we have the following bug:

1. User chooses to delete server data (we turn off replication and delete data on server)
2. Later User chooses to store data on server again
3. !! Users data does not go to server because RxDB thinks all data has already been replicated.

This feature would have a way to remove the local documents that track replication so that replication will start again from scratch.

### PR DESCRIPTION
**Pull request by chrisdrackett**
fixes #3394

## This PR contains:

 - A NEW FEATURE

## Describe the problem you have without this PR

As part of updating to 10.0 we noticed that we're getting events for the replication status when watching collection document updates. This is new and was breaking some things in our app. For now we're filtering this out by constructing the ID ourselves, but I thought others might have this same issue and it would be nice for `RxGraphQLReplicationState` to provide these id's to make it easer.

The other thing this PR does is provide a `reset` function on `RxGraphQLReplicationState`. We need this because we currently have a way for a user to delete data on our server (but not in their local app) Right now we have the following bug:

1. User chooses to delete server data 
2. User chooses to store data on server again
3. User's data does not go to server because RxDB thinks all data has already been replicated.

I figured it might be useful for others to be able to do this same thing.

## Todos 
- [X] Tests
- [ ] Documentation
- [ ] Typings
- [ ] Changelog

### CODE REVIEW

**Comment by pubkey** [comment]
Changes look good. We need at least one test for the reset function.

**Comment by special-character** [comment]
@pubkey I am working with @chrisdrackett on re-replicating our database and ran into a case that keeps some documents from replicating (even after removing and re-creating the `localDocumentStore` for the collections). 

In [crawling-checkpoint.ts](https://github.com/pubkey/rxdb/blob/master/src/plugins/replication-graphql/crawling-checkpoint.ts#L169) our document we want to re-replicate is filtered out because the `_rev` ends with the replication endpoint. It looks like this is to keep documents from replicating too many times.

We have been thinking of some solutions but don't know the full uses of the `_rev` field. One idea we had was to do some kind of bulk write to change the `_rev` property to either not include anything after the `-`, or mutate it in some other way. Do you have any inputs/ideas that might help? For `_rev`, what is the format for (it seems like the schema version and something else, maybe sequence)?

Thanks for any input!

@chrisdrackett Feel free to add anything I missed

**Comment by pubkey** [comment]
Yes RxDB uses the _rev field to track if the write came out of a graphql replication. Normally the rev field is used in couchdb do detect conflicts. But even if RxDB would use some different field, you still would have the same problem of resetting that state after you reset the replication.
When I implemented the GraphQL replication, I did not plan for that case.
Maybe we could change the behavior to not only include the endpoint hash but also another id which describes the replication instance. Then when you reset the replication, there would be a new replication instance and rxdb could know again what was already replicated and what was not.

**Comment by pubkey** [comment]
Closing this. If you still working on that please ping me so I can reopen it.

**Comment by jcs224** [comment]
I'm wondering if there's a way to do this in CouchDB replication + Dexie local driver? Even if this feature isn't added, is there guidance on which data to remove from Dexie to make it so I can replicate fresh from local device to CouchDB? Thanks!

**Pull request closed without merging**
