### PR TITLE
Add subscribe to new releases badge

### PR DESCRIPTION
**Pull request by scopsy**
## This PR contains:
 - SOMETHING ELSE

## Describe the problem you have without this PR
Allow people to subscribe to new releases of this project by e-mail. 

## Todos
- [ ] Tests
- [X ] Documentation
- [ ] Typings
- [ ] Changelog

### CODE REVIEW

**Comment by pubkey** [comment]
spam
I think you are spamming this service.
If you want updates for release, use github watch button.

release

**Comment by scopsy** [comment]
@pubkey sorry if you don't find this appropriate. I created the pull requests for the services I use and follow. GitHub does not allow me to select what version types I want to follow and I'm ending up in getting an email about every RC and patch release when I'm only interested in new features and major releases. 

The same goes for awesome-lists which github does not allow to get notifications only about new links added. 

I was thinking it might be useful for other developers as well. 
I appreciate your feedback and won't create those types of PR again.

**Comment by pubkey** [comment]
Yes it's ok for you to promote the tools you find good.
But creating mass-PRs is never wanted on github.
There were so many bots that auto-created PRs to fix typos etc. Do not do this.

**Comment by scopsy** [comment]
@pubkey Makes sense, learned my lesson. Thank you.

**Pull request closed without merging**
