### PR TITLE
adapters_doc_update

### PR DESCRIPTION
**Pull request by intersides**
documenting in the adapters page that the name property affects the data location

### CODE REVIEW

**Comment by pubkey** [comment]
Hi @intersides 
the docs are generated from the `docs-src` folder. Please do not commit generated stuff.
I think you wanted to edit [this](https://github.com/pubkey/rxdb/blob/master/docs-src/adapters.md) file

**Comment by intersides** [comment]
@pubkey , yes.. it was the case. Never too late to learn. ;)

**Comment by pubkey** [comment]
Can you update the PR and add the changes to the .md-files?

**Comment by intersides** [comment]
Yes I will… I just need some more time.

**Pull request closed without merging**
