### PR TITLE
Unit test for reproduction of issue scenario #6515

### PR DESCRIPTION
**Pull request by cayres**
## This PR contains:

Unit test for reproduction of issue scenario #6515

## Describe the problem you have without this PR

Today there is no error or event published when a client loses its websocket connection. Then we can't know and try to fix the problem, and that user doesn't get live updates anymore.

### CODE REVIEW

**Comment by pubkey** [comment]
I understand the use case.
I think this is more like feature request then a bug report.
Please make a PR if you need that feature.

**Comment by brunovinicius** [comment]
Hey Daniel! Thanks for the update. I think you are correct in that adding this event as something that we can use to react its a feature, yes. But I feel the behavior on the RxDB side is still kinda broken, I would argue.

You see, from RxDB perspective, if the websocket connection fails or gets dropped, a new one is created to re-stablish communication. I would argue this scenario is one that should cause the same behavior as when a GraphQL subscription gets dropped.

**Comment by pubkey** [comment]
Dropped subscriptions that reconnect could lead to missed events on the client that happen during this time. Please consider that case when implementing.

**Comment by cayres** [comment]
Hi Daniel, I have started coding this feature and realized that this was solved in the PR #6598. With the exposed wsoptions it is possible to listen to the closed events and reconnect. So I think this issue can be closed.

**Comment by cayres** [comment]
Hi Daniel, I have started coding this feature and realized that this was solved in the PR #6598. With the exposed wsoptions it is possible to listen to the closed events and reconnect. So I think this issue can be closed.

**Pull request closed without merging**
