### PR TITLE
Add schema object type detection for nullable property & Add support for nested array in getSchemaByObjectPath

### PR DESCRIPTION
**Pull request by sdoubey**
Add schema object type detection for nullable property
Add support for nested array in getSchemaByObjectPath

## This PR contains:
 - A BUGFIX
 - A NEW FEATURE

## Describe the problem you have without this PR
Nested array were not supported because path was badly computed
`dbQuery.sort({'localizations.0.title': 'asc'})` didn't work, so i changed regex replace with
```
usePath = usePath.replace(/\.([a-z])/g, '.properties.$1');
usePath = usePath.replace(/\.([0-9]+)/g, '.items.$1');
```
And now it works.
_Don't forget to add `compoundIndexes: [['localizations.0.title']]`_

Nullable property could have wrong type because it's an array, for exemple
```
authorId: {
 type: ['string', 'null'],
}
```
trigger default case of switch, so i added 
```
const schemaType = Array.isArray(schemaObj.type) ? schemaObj.type.find((type: any) => type !== 'null') : schemaObj.type;
```

## Todos
- [ ] Tests
- [ ] Documentation
- [ ] Typings
- [ ] Changelog

### CODE REVIEW

**Comment by pubkey** [comment]
Hi @sdoubey 
Thank you for the PR. The code looks good.
Can you add some tests to that so we can be sure this will not break in the future?

**Comment by pubkey** [comment]
I added a test but it did not work even with your changes

```typescript
        it('#1945 Nested array were not supported because path was badly computed', async () => {
            // create a schema
            const mySchema: RxJsonSchema = {
                version: 0,
                type: 'object',
                properties: {
                    passportId: {
                        type: 'string',
                        primary: true
                    },
                    localizations: {
                        type: 'array',
                        items: {
                            type: 'object',
                            properties: {
                                title: {
                                    type: 'string'
                                }
                            }
                        }
                    },
                    authorId: {
                        type: ['string', 'null'],
                    }
                },
                compoundIndexes: [['localizations.0.title']]
            };
            const db = await RxDB.create({
                name: util.randomCouchString(10),
                adapter: 'memory',
                queryChangeDetection: true,
                ignoreDuplicate: true
            });

            // create a collection
            const collection = await db.collection({
                name: 'mycollection',
                schema: mySchema
            });

            // insert documents
            await collection.bulkInsert([
                {
                    passportId: 'doc1',
                    localizations: [{ title: 'bob' }]
                }, {
                    passportId: 'doc2',
                    localizations: [{ title: 'alice' }]
                }
            ]);
            const sortedByTitleAsc = await collection.find().sort({ 'localizations.0.title': 'asc' }).exec();
        });
```
```bash
init.test.js: unhandledRejection
RxError: RxError:
SchemaCheck: given index is not defined in schema
Given parameters: {
key:"localizations.0.title"}
    at newRxError (/home/dnl/workspace/rxdb/src/rx-error.ts:107:12)
    at /home/dnl/workspace/rxdb/src/plugins/schema-check.ts:273:23
    at Array.map (<anonymous>)
    at checkSchema (/home/dnl/workspace/rxdb/src/plugins/schema-check.ts:269:10)
    at /home/dnl/workspace/rxdb/src/hooks.ts:58:35
    at Array.forEach (<anonymous>)
    at runPluginHooks (/home/dnl/workspace/rxdb/src/hooks.ts:58:20)
    at createRxSchema (/home/dnl/workspace/rxdb/src/rx-schema.ts:367:9)
    at RxDatabaseBase.collection (/home/dnl/workspace/rxdb/src/rx-database.ts:251:24)
    at _callee49$ (/home/dnl/workspace/rxdb/test/unit/rx-query.test.ts:1474:41)
    at tryCatch (/home/dnl/workspace/rxdb/node_modules/regenerator-runtime/runtime.js:45:40)
    at Generator.invoke [as _invoke] (/home/dnl/workspace/rxdb/node_modules/regenerator-runtime/runtime.js:274:22)
    at Generator.prototype.<computed> [as next] (/home/dnl/workspace/rxdb/node_modules/regenerator-runtime/runtime.js:97:21)
    at asyncGeneratorStep (/home/dnl/workspace/rxdb/node_modules/@babel/runtime/helpers/asyncToGenerator.js:3:24)
    at _next (/home/dnl/workspace/rxdb/node_modules/@babel/runtime/helpers/asyncToGenerator.js:25:9) {
  code: 'SC21',
  parameters: { key: 'localizations.0.title' },
  rxdb: true
}
```


Can you please check?

**Comment by sdoubey** [comment]
> I added a test but it did not work even with your changes
> 
> ```ts
>         it('#1945 Nested array were not supported because path was badly computed', async () => {
>             // create a schema
>             const mySchema: RxJsonSchema = {
>                 version: 0,
>                 type: 'object',
>                 properties: {
>                     passportId: {
>                         type: 'string',
>                         primary: true
>                     },
>                     localizations: {
>                         type: 'array',
>                         items: {
>                             type: 'object',
>                             properties: {
>                                 title: {
>                                     type: 'string'
>                                 }
>                             }
>                         }
>                     },
>                     authorId: {
>                         type: ['string', 'null'],
>                     }
>                 },
>                 compoundIndexes: [['localizations.0.title']]
>             };
>             const db = await RxDB.create({
>                 name: util.randomCouchString(10),
>                 adapter: 'memory',
>                 queryChangeDetection: true,
>                 ignoreDuplicate: true
>             });
> 
>             // create a collection
>             const collection = await db.collection({
>                 name: 'mycollection',
>                 schema: mySchema
>             });
> 
>             // insert documents
>             await collection.bulkInsert([
>                 {
>                     passportId: 'doc1',
>                     localizations: [{ title: 'bob' }]
>                 }, {
>                     passportId: 'doc2',
>                     localizations: [{ title: 'alice' }]
>                 }
>             ]);
>             const sortedByTitleAsc = await collection.find().sort({ 'localizations.0.title': 'asc' }).exec();
>         });
> ```
> 
> ```shell
> init.test.js: unhandledRejection
> RxError: RxError:
> SchemaCheck: given index is not defined in schema
> Given parameters: {
> key:"localizations.0.title"}
>     at newRxError (/home/dnl/workspace/rxdb/src/rx-error.ts:107:12)
>     at /home/dnl/workspace/rxdb/src/plugins/schema-check.ts:273:23
>     at Array.map (<anonymous>)
>     at checkSchema (/home/dnl/workspace/rxdb/src/plugins/schema-check.ts:269:10)
>     at /home/dnl/workspace/rxdb/src/hooks.ts:58:35
>     at Array.forEach (<anonymous>)
>     at runPluginHooks (/home/dnl/workspace/rxdb/src/hooks.ts:58:20)
>     at createRxSchema (/home/dnl/workspace/rxdb/src/rx-schema.ts:367:9)
>     at RxDatabaseBase.collection (/home/dnl/workspace/rxdb/src/rx-database.ts:251:24)
>     at _callee49$ (/home/dnl/workspace/rxdb/test/unit/rx-query.test.ts:1474:41)
>     at tryCatch (/home/dnl/workspace/rxdb/node_modules/regenerator-runtime/runtime.js:45:40)
>     at Generator.invoke [as _invoke] (/home/dnl/workspace/rxdb/node_modules/regenerator-runtime/runtime.js:274:22)
>     at Generator.prototype.<computed> [as next] (/home/dnl/workspace/rxdb/node_modules/regenerator-runtime/runtime.js:97:21)
>     at asyncGeneratorStep (/home/dnl/workspace/rxdb/node_modules/@babel/runtime/helpers/asyncToGenerator.js:3:24)
>     at _next (/home/dnl/workspace/rxdb/node_modules/@babel/runtime/helpers/asyncToGenerator.js:25:9) {
>   code: 'SC21',
>   parameters: { key: 'localizations.0.title' },
>   rxdb: true
> }
> ```
> 
> Can you please check?

Hi, 
I just commit some updates, i had to make some updates in schema-check.ts because schema check regex has to be updated here too, and i saw that your "items" property in your schema was an object, but i don't know why it has to be an array to works with couchdb layer.... so i change your test schema and change regex in schema-check.ts to accept number property name

I added the test in "rx-query.test.ts":
`
describe('nested array', () => {
        it('should be used in sort', async () => {....}
}
`

I ran npm run-script test:node and everything was OK.

**Comment by pubkey** [comment]
The CI is green now.
But I think we should not diverge from the jsonschema standard for [arrays](https://json-schema.org/understanding-json-schema/reference/array.html)
Since couchdb has no schema I think this is something that has to be fixed in RxDB.

**Comment by pubkey** [comment]
Closing this bc no answer. The fix is still wanted. Please reopen with a fix that applies to the jsonschema standard.

**Pull request closed without merging**
