### PR TITLE
fix(src:plugins:utils): properly call hasOwnProperty in deepFreeze util

### PR DESCRIPTION
**Pull request by emil14**
## This PR contains:

 - A BUGFIX

## Describe the problem you have without this PR

#5382

### CODE REVIEW

**Comment by pubkey** [comment]
Hi @emil14  The fix looks good to me. Do you think it is possible to reproduce the problem in a unit test? Then we could be sure that this does not break again in the future.

**Comment by emil14** [comment]
@pubkey hey there

Unfortunately I don't I have time for that now, this will require diving into the structure of the repository.

I suggest you enable https://eslint.org/docs/latest/rules/no-prototype-builtins this linter, this problem could arrive not only in that piece of code but literally everywhere you use methods defined on `Object` because of how JavaScript works. One unit test won't protect anyway

**Comment by pubkey** [comment]
@emil14  thanks for the suggestion. I am working on enabling the linting rule here https://github.com/pubkey/rxdb/pull/5398

**Comment by pubkey** [comment]
Closed in favor of https://github.com/pubkey/rxdb/pull/5398

**Pull request closed without merging**
