### PR TITLE
CouchDB Replication

### PR DESCRIPTION
**Pull request by Unforgiven-wanda**
Hello again,
CouchDB replication is essentially broken in this state because it has issues that do not appear when using Pouchdb-server in tests.
To test this pull request you'll have to have an instance of CouchDB running, either locally or not.
I've been at this for a few days, and I can tell you there are three main issues when replicating with CouchDB:

1. The one detailed in this test: If the database you replicate to contains `deleted` documents, the initial replication will fail with `Cannot read properties of null (reading 'id')`. In the test present in this pull request, we create a pristine CouchDB database, sync to it 3 created documents, delete two and then destroy the DB. Upon running the test again however, this error will throw on initial replication.
2. `Ensurenotfalsy` that we thought fixed in https://github.com/pubkey/rxdb/commit/657de005c6b45f4218d03a9c8e79c1cd3738360b is still present, but ever more randomly, I haven't been able to reproduce this reliably with CouchDB replication, but as far as I can tell, it doesn't happen anymore with PouchDB-server in tests. It might occur after 2 edits or a hundred, and honestly I am stumped when it comes to this one.
3. Downstream replication will not occur if the document has been edited locally (**Always in CouchDB replication, not Pouchdb-server**). Edits on CouchDB's Fauxton (or other users) are replicated fine on app start, but the second you edit a document, it ceases to receive downstream updates. I have inquired about this [here](https://github.com/pubkey/rxdb/issues/4285#issuecomment-1386765617).

In its current state, CouchDB replication has too many issues that do not pop up in unit tests, because those use PouchDB-server. What the differences between the two are I do not know, but there has to be some glaring ones because they behave completely differently in the issues I have pointed out above.
I will try to create tests for the two other issues once we hopefully fix the first one.
As always, thank you for your invaluable time.

### CODE REVIEW

**Comment by pubkey** [comment]
@Unforgiven-wanda I tried running the current tests against a real couchdb server. You are right, nothing works. Give me some time to fix the basics, then we can check if your issues are also solved.

**Comment by pubkey** [comment]
@Unforgiven-wanda I added a test run `npm run test:replication-couchdb` which runs the couchdb replication tests against a native couchdb server. Please add your tests there so we can reproduce your problem.

**Comment by Unforgiven-wanda** [comment]
@pubkey It seems the issues listed above only occur on CouchDB 3.x. When testing against CouchDB 2.3.1 the only issue that remains is the one where downstream replication doesn't happen. Switch docker to CouchDB 3.2.2 and it occurs again.
So our culprit here was CouchDB 3.x all along.

I have added a `test:replication-couchdb3` npm command for you look at.

I will adapt the test for failing downstream replication for Couchdb2 as soon as I can.

**Comment by pubkey** [comment]
@Unforgiven-wanda  I updated the tests to use couchdb v3 here: https://github.com/pubkey/rxdb/pull/4336
But there it works, so I have no idea what you are doing wrong.

**Comment by pubkey** [comment]
I added some more tests. I think that is all I can do.

**Comment by Unforgiven-wanda** [comment]
Please give me a couple days before closing this eventually. I've been bombarded with unexpected work and haven't had time to look through this.
As always, thank you for your time.

**Comment by pubkey** [comment]
@Unforgiven-wanda No hurry. The v14 will be in beta for 3-4 more weeks. I can leave this open.

**Comment by Unforgiven-wanda** [comment]
Small addition to `should stream changes over the replication to a query` test, demonstrating how edits directly on the CouchDB instance aren't reflected on the local database.

**Comment by pubkey** [comment]
@Unforgiven-wanda 
I think I found the root problem. In v13 the assumption was that RxDB creates the exact same md5 hash revisions as CouchDB would create. But this is not true for v14. I refactored the whole revisision and conflict handling for the CouchDB replication here https://github.com/pubkey/rxdb/pull/4348

**Comment by Unforgiven-wanda** [comment]
Downstream replication is fixed. And I haven't been able to reproduce the other issues since, so I'm assuming (here's hoping) they're also fixed.
Closing this then.
Please allow me to thank you once again for your fantastic work and time invested. You are a prince among open-source maintainers.
Have a wonderful week.

**Comment by pubkey** [comment]
@Unforgiven-wanda great. Thank you for the investigation. Releasing a broken CouchDB replication while removing PouchDB support would be painful :)

**Comment by mbret** [comment]
I am using the v14 with a 3.2 couchdb server and I still have the downstream replication broken together with upstream (randomly). Another big problem is as soon as you get offline, the replication will continuesly loop on request retry and do a thousands of requetes per seconds.

**Comment by pubkey** [comment]
Make  PR with a failing test.

**Pull request closed without merging**
