### PR TITLE
Test for #4948 (RxDocument.get() on additonalProperty)

### PR DESCRIPTION
**Pull request by adam-lynch**
## This PR contains:
 - IMPROVED TESTS

## Describe the problem you have without this PR
This contains a test for #4948

### CODE REVIEW

**Comment by pubkey** [comment]
Hi @adam-lynch 
I am not sure if this test is what you want it to be:
The test breaks because `assert.strictEqual(myDocument.get('tags'), tags);` throws.
But the `tags` object is never `strictEqual` to the thing you get from `get('tags')`, because RxDB will add getters for the population and observable fields.

Checking if the content is the same, works

```ts
 assert.deepStrictEqual(myDocument.get('tags').hello, tags.hello);
assert.deepStrictEqual(myDocument.get('tags').world, tags.world);
```

Also this is why `toJSON().tags` is strict equal, because toJSON() returns the plain data object, without any RxDB specific getters/setters.

**Comment by adam-lynch** [comment]
@pubkey ah yes, I've improved the test now. While what you said is true, it's still failing now; both `.get('tags')` and `.tags` have unexpected extra fields (`additionalProperties` and `type`).

**Comment by pubkey** [comment]
Can you rebase so that the CI can run?

**Comment by pubkey** [comment]
RxDB uses a prebuild constructor (per collection) to create the RxDocument from the documentData that comes out of the storage.
This constructor knows all getters/setters, ORM methods and so on. This makes creating the RxDocument much faster compared to cloning the data and adding these things to each document object.
Therefore it does not add getters for fields that are not known at collection-creation time (=fields that are not in the schema).

The only other options would be the proxy API, but the Proxy API is [so slow](https://thecodebarbarian.com/thoughts-on-es6-proxies-performance) that I do not want to use it for accessing document properties, because the performance is so important at this.

So atm `toJSON()...` is the only way to get your additional properties. Atm I am not sure how this could be fixed.

**Comment by adam-lynch** [comment]
OK I understand; if we want to use `additionalProperties: true`, we must access it via `toJSON()` / `toMutableJSON()`.

**Comment by pubkey** [comment]
Yes, atm you need `toJSON()`.
I see some options on how to fix that in the future, please leave this PR open.

**Comment by pubkey** [comment]
I did some performance tests and refactorings. This will be fixed in the next major version.

**Pull request closed without merging**
