### PR TITLE
Update alternatives.md

### PR DESCRIPTION
**Pull request by beorn**
Add more alternatives: InstantDB, ElectricSQL, SignalDB, PowerSync, SQLSync

## Todos 
- [ ] Tests
- [ ] Documentation
- [ ] Typings
- [ ] Changelog

### CODE REVIEW

**Comment by pubkey** [comment]
Some parts of these texts are wrong. Did you use ChatGPT?

**Comment by pubkey** [comment]
Its like everything is just slightly wrong a bit. Please write it by yourself.
As alternative we can just add a link-list at the bottom so that we at least do not missinform readers.

**Comment by beorn** [comment]
I'll go over it again and try to fact-check it more, and maybe make some entries a bit shorter.  I wish there was another more comprehensive list of local-first technologies that you could point to, but this one is actually the most comprehensive I've seen so far :)  In any case, it's useful to compare them to RxDB. It's also fast-moving field so my worry it'll be outdated very quickly.

**Comment by beorn** [comment]
I made another round of edits.  It's somewhat difficult to compare and contrast the alternatives given they are so different and (often) flexible, and giving a pros/cons list is ultimately going to be a bit subjective.  Perhaps there are other things you want to mention or leave out, or emphasize/deemphasize.

**Comment by beorn** [comment]
This comparison maybe interesting as it highlights internals of PowerSync and Electric-Next - https://www.powersync.com/blog/electricsql-electric-next-vs-powersync

**Comment by pubkey** [comment]
Thank you, this looks way better. Merged.

**Pull request merged**
