### PR TITLE
Fix ability to set PouchDB settings

### PR DESCRIPTION
**Pull request by labibramadhan**
Hi @pubkey, please have a look, i think this PR useful for setup the PouchDB settings for example: set the persistent/temporary database type on IndexedDB adapter

### CODE REVIEW

**Comment by labibramadhan** [comment]
Hi @pubkey, i think this PR useful for setup the PouchDB settings for example: set the persistent/temporary database type on IndexedDB adapter

**Comment by pubkey** [comment]
Hi @labibramadhan 
Please check out the current [dev-branch](https://github.com/pubkey/rxdb/blob/3.0.0/src/RxCollection.js#L644)

**Comment by labibramadhan** [comment]
Version 2 will no longer maintained?

**Comment by pubkey** [comment]
Oh big sry. My bad.
I thought [this](https://github.com/pubkey/rxdb/pull/63/files#diff-da6aba656724ec0d4c95da7a0c781e1eR429) is also done in version 2.0.0

Could you make the parameter optional at the typings [here](https://github.com/pubkey/rxdb/pull/63/files#diff-b739f95ace6bbf2f0fd5e8cf1dab97d8R25)?

**Comment by labibramadhan** [comment]
Allright sir, there you go

**Comment by pubkey** [comment]
Merged. I will do a new build on v2 tomorrow.

**Comment by pubkey** [comment]
@labibramadhan I published the new version a few minutes ago.

**Comment by labibramadhan** [comment]
nice mate, thanks 👍

**Pull request merged**
