### PR TITLE
react-native-bare example with premium sqlite

### PR DESCRIPTION
**Pull request by msotnikov**
bare react-native example.
It reproduce the bug with rxdb-premium when creating database

```
 LOG  open transaction error (will retry):
 LOG  open transaction error (will retry):
 LOG  open transaction error (will retry):
 LOG  open transaction error (will retry):
 LOG  open transaction error (will retry):
 LOG  open transaction error (will retry):
 LOG  open transaction error (will retry):
```

### CODE REVIEW

**Comment by pubkey** [comment]
Thank you, I will check.

**Comment by pubkey** [comment]
I started this with android studio and everything works for me, so I am not sure what is wrong.
I will release a new rxdb-premium version in a few minutes that contains improved error logging.
Please update to that one so we can better check what is going wrong.

**Comment by pubkey** [comment]
I am not able to run your example:

```
 WARN  Possible Unhandled Promise Rejection (id: 0):
TypeError: t is not a function. (In 't({
              name: o
            }, exports.EMPTY_FUNCTION, exports.EMPTY_FUNCTION)', 't' is undefined)
```

**Comment by pubkey** [comment]
I updated quick sqlite to version 6.1.0 `"react-native-quick-sqlite": "6.1.0"`
and made some changes to `getSQLiteBasicsQuickSQLite`. Please try out the latest rxdb versions

**Comment by msotnikov** [comment]
Yes, now it works! Thanks a lot!

Should we finish this PR to make it work?

**Comment by msotnikov** [comment]
Ok

**Pull request closed without merging**
