### PR TITLE
Add test for firestore replication bug

### PR DESCRIPTION
**Pull request by chrisdrackett**
## Describe the problem you have without this PR
When adding items quickly while using firestore replication, only the first change makes it onto the server. Also, in this case changes from the server don't automatically make it back to the client.

### CODE REVIEW

**Comment by pubkey** [comment]
Can you reproduce the problem with a non-firestore replication?

**Comment by chrisdrackett** [comment]
@pubkey hm, I just tried this in a graphQL replication test and I'm pretty sure I'm seeing the same thing. I feel like I'm stumbling around these tests a bit, so here is the code I used:

```
                await c.insert(schemaObjects.humanWithTimestamp({id: 'a123456', name: '1'}));

                await waitUntil(() => pushCount === 1);

                await c.incrementalUpsert({id: 'a123456', name: '2'})
                await c.incrementalUpsert({id: 'a123456', name: '3'})

                await waitUntil(() => pushCount === 3);

                const docsOnServer = server.getDocuments()[0];
                assert.strictEqual(docsOnServer.name, '3');
```

in this the assert is getting `1` vs. the expected `3`.

```
AssertionError [ERR_ASSERTION]: Expected values to be strictly equal:

'1' !== '3'
```

**Comment by chrisdrackett** [comment]
@pubkey curious if you've been able to replicate this issue. I'm attempting to work around it or figure out what is going on. I want to make sure this is an RxDB issue and not something I'm doing in my code (mostly surprised I'm the first to run into this)

**Comment by pubkey** [comment]
No I had no time working on this.
The first step would be to reproduce this with the plain non-firebase replication-protocol to ensure that this is not a firebase issue.

**Comment by pubkey** [comment]
Can you make a PR with a failing test that uses graphql instead of firestore?

**Comment by pubkey** [comment]
Ok, this helps to understand.
Please notice that firestore replication is on beta, so I will likely not fix that by myself.

**Comment by chrisdrackett** [comment]
@pubkey oh, is there no plan for official firestore support? I figured the beta tag was because it was still in active development and not ready for production. Is there anyone else I can ping about this?

**Comment by pubkey** [comment]
There is a plan for official support. But it is an open source project, so it is assumed that the community fixes the bugs, not solely the maintainer.

**Comment by chrisdrackett** [comment]
totally get it, I spent a little over a day trying to fix this but didn't get very far as the way replication works in RxDB is over my head :D

**Comment by pubkey** [comment]
I am closing this. I cannot fix it without reproduction. Please make a PR with a failing test case.

**Comment by chrisdrackett** [comment]
@pubkey this pr is a failing test case?

**Comment by pubkey** [comment]
@chrisdrackett I am so sorry. You are right. Reopened.

**Comment by pubkey** [comment]
I think in your test you forgot to run `await replicationState.awaitInSync();` after the last document update. At the time you check the correctness of the server docs, you cannot assume that the replication is done already. It might be still transfering data.

https://github.com/pubkey/rxdb/pull/5240

**Comment by pubkey** [comment]
@chrisdrackett  can you check if this fixes your problem?

**Comment by chrisdrackett** [comment]
@pubkey I think this did it. I'm also going to submit a PR to update the docs for `incrementalUpsert()` as that is where I got the non-awaited code.

**Pull request closed without merging**
