### PR TITLE
Couchdb replication bug report

### PR DESCRIPTION
**Pull request by Unforgiven-wanda**
Hello,
As requested, here is a pull that reproduces the CouchDB replication bug.
Had to add `node-fetch@2` because replication `fetch` would fail during the test.
Other than that just have a CouchDB instance running, edit the credentials and give it a try.

As always, thank you for your time.

### CODE REVIEW

**Comment by pubkey** [comment]
If the normal node fetch does not work, we should fix that first.
In the tests we normally use the pouchdb server as couchdb endpoint, does it also fail with that?

**Comment by Unforgiven-wanda** [comment]
@pubkey I tested it just now with `pouchdb-server` and received the exact same error.

**Comment by pubkey** [comment]
Pls adapt the test so that the CI reproduces your problem

**Comment by Unforgiven-wanda** [comment]
Done.

**Comment by pubkey** [comment]
Thank you so much. Fixed in 657de005c6b45f4218d03a9c8e79c1cd3738360b

**Pull request closed without merging**
