### PR TITLE
improve index.d.ts

### PR DESCRIPTION
**Pull request by Jimmysh**
export PouchDB for check adapter can use.

const db = new PouchDB('mydb', { adapter: adapter });
return db.info();

### CODE REVIEW

**Comment by pubkey** [comment]
Hi @Jimmysh 
I added the param-name to the create-function.
I don't get what the pouchdb-export should do?
There is no collection-method in pouchdb

**Comment by Jimmysh** [comment]
`
function checkAdapterWorks(adapterName: string) {
  try {
    const db = new PouchDB('testDB', { adapter: adapterName });
    return !!db.info();
  } catch (e) {
  }
  return false;
}
const adapters: {
  name: string,
  entity: any
}[] = [
    { name: 'idb', entity: idb },
    { name: 'websql', entity: websql },
    { name: 'localstorage', entity: localstorage },
    { name: 'memory', entity: memory },
  ];

 const find = _.find(adapters, (adapter: any) => checkAdapterWorks(adapter.name));
    if (find) {
      this.useAdapter = find;
      console.log('current adapter', this.useAdapter);
    } else {
      console.log('don't support');
    }

`
sample.

**Comment by pubkey** [comment]
You defined the function `PouchDB.collection` [here](https://github.com/pubkey/rxdb/pull/125/files#diff-b739f95ace6bbf2f0fd5e8cf1dab97d8R199).
But as far as I know, this function does not exists?

**Comment by pubkey** [comment]
Merged, thank you @Jimmysh 
Maybe we can find a way to directly import the typings of pouchdb, like [this ones](http://definitelytyped.org/docs/pouchDB--pouch/globals.html#pouchdb)

**Comment by pubkey** [comment]
The last commit was added here by mistake. Just ignore it.

**Pull request merged**
