### PR TITLE
query will never executed in some cases

### PR DESCRIPTION
**Pull request by 4321ip**
https://github.com/pubkey/rxdb/issues/3569
way to reproduce:
1. clone the whole [RxDB-repo](https://github.com/pubkey/rxdb)
2. go into project `cd rxdb`
3. run `npm install`  (you may need to run `npm install --legacy-peer-deps`)
4. go to this folder `cd examples/graphql`
5. run `npm install`
6. run `npm start`
7. open two tabs ~http://localhost:8888/~ [http://localhost:8888/?storage=lokijs&sync=false](http://localhost:8888/?storage=lokijs&sync=false)
8. on last tab - click "insert btn"
9. wait for 3 second

### CODE REVIEW

**Comment by pubkey** [comment]
@4321ip thank you for providing more information.
So the `alert('FREEZE')` will fully block the JavaScript process. When the process is blocked, it cannot respond to a request from the other tab. If I understand this right, there is not much that can be done here.

**Comment by pubkey** [comment]
Ah sorry. Now I understand. Event when the alert box is closed and the process is free again, the query does not finish.
I will investigate..

**Comment by pubkey** [comment]
Ok so I checked again and there are multiple things that are unclear.
- Why do you call `.remove()` on the collection if it exists? This will delete all data and when it runs while the collection is removed, it leads to undefined behavior.
- Why is `multiInstance: true` set? This is meant for testing only. Can you reproduce the problem without creating a new database instance on each insert?

**Comment by 4321ip** [comment]
@pubkey 
with multiInstance=false the problem is gone, but rxdb is useful due to Multi-Tab support(espesially with lokiJs)
i call collection.remove() in my project when user logout to delete some sensitive data.
common workflow:
```
async logout() {
await collection1.remove()
await collection2.remove()
.....
await createCollection()
await createCollection()
}
```

**Comment by pubkey** [comment]
@4321ip 
I added a fix now that ensures that the remote operation re-runs when the leader dies.
See 06d0b79777d0950e22756c56e98c44a6364b3c77
This is released in the latest beta version. Please check if this fixes your problem.

**Comment by pubkey** [comment]
@4321ip 
I think I found it now. Released `11.0.0-beta.13`
It was an error in the broadcast-channel module where events got missed because of inacurate javascript timing.
[See](https://github.com/pubkey/broadcast-channel/commit/91a3e648ad0ffb58acd6267f8ee063d6d5e115ad#diff-845a6b22541d2f98bc0055d168291df1175041abe8117b54677b29fe9db8c0afR247-R263)

**Comment by 4321ip** [comment]
@pubkey 
Sorry to tell you, but still doesn't work

**Comment by pubkey** [comment]
We need a test to reproduce this. 
The current code calls collection.remove() and recreates the collection. I am not sure if this is supposed to work.

**Comment by 4321ip** [comment]
> Multi-Tab

**Comment by 4321ip** [comment]
> We need a test to reproduce this. The current code calls collection.remove() and recreates the collection. I am not sure if this is supposed to work.
@pubkey 
its works! But only without multiTab support

**Pull request closed without merging**
