### PR TITLE
Fixes #126 Error on npm start running angular2 example Fixes #128 Error in browser console running angular2 example

### LINKED ISSUE #126: Error on npm start running angular2 example
## Case
Bug

## Issue
When following the steps in the README of examples/angular2 the following error occurs after `npm start`:

`ERROR in [at-loader] TS2468: Cannot find global value 'Promise'.`

### LINKED ISSUE #128: Error in browser console running angular2 example
## Case
Bug

## Issue
When running the angular2 example
- the page just shows 'Loading...'
- there is a bug in the browser console: `Uncaught ReferenceError: regeneratorRuntime is not defined`

### PR DESCRIPTION
**Pull request by rdworth**
Per https://github.com/AngularClass/angular2-webpack-starter/issues/930\#issuecomment-243594616

### CODE REVIEW

**Comment by pubkey** [comment]
I don't think we should change the target to es6. I added a commit which just adds the polyfills. This works now for me (redo `npm i`). Please reopen if it does not work for you.

**Comment by rdworth** [comment]
@pubkey I'm getting the same error when I `npm start` with your polyfill fix

**Comment by pubkey** [comment]
Did you `rm -r node_modules` and `npm i` again?

**Comment by rdworth** [comment]
Sorry. I was careful to do that (`rm -r node_modules` and `npm i`) but I had fetched upstream and then failed to merge it. All good. Thanks

**Pull request closed without merging**
