### PR TITLE
Issue report: idb adapter: second remove w/ same primary key raises exception, no bugfix

### PR DESCRIPTION
**Pull request by kac-**
To reproduce:
1. use *idb* storage
1. insert document w/ primaryKey *X*
1. *remove()* this document
1. once again create document w/ primary key *X*
1. *remove()* on this document raises exception

Issue doesn't show up:
- with *indexeddb* storage
- when you reopen database between steps *4* and *5*

### CODE REVIEW

**Comment by kac-** [comment]
I tried but cannot reproduce it w/ plain PouchDB and simple `put()/remove()`

**Comment by pubkey** [comment]
Can you add that to the test?

**Comment by kac-** [comment]
**UPDATE**:
When you do `atomicPatch()` instead of second `remove()` rxdb ends with infinite loop.

There are also differences between *idb* and *indexeddb* while listening to `db.heroes.storageInstance.internals.pouch.changes()`

Code sequence:
- create
- delete
- create
- atomicPatch

With **indexeddb** it generates:

```
{"id":"uniqueID","changes":[{"rev":"1-9cfb7fcbcd46e7b4cf4d2022d8e245e3"}],"seq":1}
{"id":"uniqueID","changes":[{"rev":"2-c60bac2fe079266c0384e88b4bbed4c1"}],"deleted":true,"seq":2}
{"id":"uniqueID","changes":[{"rev":"1-388273fc4f94b4835b9096cc74659288"}],"seq":3}
{"id":"uniqueID","changes":[{"rev":"2-d1d11c0c820b9bffa740bbf41dfe19d0"}],"seq":4}
```

With **idb** it generates:

```
{"id":"uniqueID","changes":[{"rev":"1-1c93285f00f7bddeab4edc69fe877cd9"}],"seq":1}
{"id":"uniqueID","changes":[{"rev":"2-3214171281cc0dd9a7d1eb2f6fcd4752"}],"deleted":true,"seq":2}
{"id":"uniqueID","changes":[{"rev":"3-06f362cc14889fc477001bf2e13628ee"}],"seq":3}
```

And loops.

**Comment by kac-** [comment]
Looks like related to [plugins/puchdb/custom-events-plugin](https://github.com/pubkey/rxdb/blob/master/src/plugins/pouchdb/custom-events-plugin.ts) but I'm to short for it :)

**Comment by pubkey** [comment]
> Code sequence:
create
delete
create
update


When you do the same sequence with plain pouchdb, does that work?

**Comment by pubkey** [comment]
Please make a PR with a test that proves that this is a RxDB problem and it works with plain pouchdb.

**Pull request closed without merging**
