### PR TITLE
build: bump ws version

### PR DESCRIPTION
**Pull request by tychoprice**
## This PR contains:
BUGFIX

## Describe the problem you have without this PR
https://github.com/pubkey/rxdb/issues/6326

### CODE REVIEW

**Comment by pubkey** [comment]
This fails the CI, please check.

**Comment by pubkey** [comment]
@tychoprice Please check

**Comment by G-Rath** [comment]
Related #6182 - just as an extra data point, we've forced `rxdb` to use v8.18.0 and had that in production since July without issue; I can't say we're using all the features but still it's a useful data point.

**Comment by pubkey** [comment]
Closing this because no answer. PRs must not fail the CI to be merged, please check.

**Pull request closed without merging**
