### PR TITLE
feat: adding support for esm modules entries

### PR DESCRIPTION
**Pull request by SebasG22**
## Describe the problem you have without this PR

This PR fixes the issue on some javascript environments (Sveltekit) when you get a resolution error for plugins dependencies as

```
Error [ERR_UNSUPPORTED_DIR_IMPORT]: Directory import 'C:\Users\SebasG\Documents\svelte-kit-demo\node_modules\rxdb\plugins\query-builder' is not supported resolving ES modules
```

### How was fixed?
Adding entries to the package JSON to ensure the validation works correctly. 

After this PR is merged we can add a sveltekit example to test this issue and support it.

### CODE REVIEW

**Comment by pubkey** [comment]
Related: https://github.com/pubkey/rxdb/pull/4179

**Comment by pubkey** [comment]
Hi.
Since this adds the `exports` fields to the package.json, should that make the `package.json` files for individual plugins in [this folder](https://github.com/pubkey/rxdb/tree/master/plugins) obsolete?
Also should we set `"type": "module"` in the root package.json?

My knowledge arround the whole module/csm/esm/export syntax is lacking, so I might be wrong.

Is this a breaking change? Because for the next major release, there is the [feature/14.0.0](https://github.com/pubkey/rxdb/pull/4181) branch.

**Comment by SebasG22** [comment]
I wasn't able to test this change against the premium plugins due to

> Hi. Since this adds the `exports` fields to the package.json, should that make the `package.json` files for individual plugins in [this folder](https://github.com/pubkey/rxdb/tree/master/plugins) obsolete? Also should we set `"type": "module"` in the root package.json?
> 
> My knowledge arround the whole module/csm/esm/export syntax is lacking, so I might be wrong.
> 
> Is this a breaking change? Because for the next major release, there is the [feature/14.0.0](https://github.com/pubkey/rxdb/pull/4181) branch.

Hey @pubkey,
Additionally, I could not test this change in projects that include the premium plugins because I don't have access to it.
If you want I can do some tests

I am going to do some testing to see if it is possible to remove the package.json from each plugin. Although initially I don't think it would be a good idea, I want to explore it.

I don't consider it a breaking change, since on the user side it shouldn't change the implementation at all. But I'm not sure what standard you are using to consider something minor or major.

**Comment by pubkey** [comment]
>  I could not test this change in projects that include the premium plugins because I don't have access to it

I will fix these afterwards by myself, they anyway run in a different project so it will not fail the rxdb CI.

I think the way rxjs does it is the way to go https://github.com/ReactiveX/rxjs/blob/master/package.json and they also do not have differente package.json files.

I am not sure if this is a breaking change but I would prever to release it on 14.0.0 because the chances are high that it will break some peoples build configuration.

**Comment by SebasG22** [comment]
We are aligned in the way RXJS handles exports in the json package.

Currently removing the package.json inside the plugin folder breaks all the code imports because they are always pointing to dist instead of itself.

I consider that this is a first step on the way to improving the codebase, which can be merged and then make a refactoring where you have a package.json for each plugin for this purpose.

If you merge this to master, can you backport it to the release branch?

**Comment by swnf** [comment]
> I think the way rxjs does it is the way to go https://github.com/ReactiveX/rxjs/blob/master/package.json and they also do not have differente package.json files.

@pubkey I think rxjs does not have multiple `package.json` in their github repo, but the package on npm contains different `package.json` for the paths:

```
./fetch/package.json
./ajax/package.json
./webSocket/package.json
./package.json
./operators/package.json
./testing/package.json
```

**Comment by pubkey** [comment]
@swnf Ah yes indeed they have.
So we should do the same. So the only thing missing is to generate the `plugins/` folder from the content of the root package.json during build time.

**Comment by pubkey** [comment]
Merged, I added the generation of the package.json files on the master branch.

**Pull request merged**
